version: "3.8"

services:
  postgres:
    image: postgres:alpine
    restart: always
    env_file:
      - ../dev.env
    ports:
      - "5434:5432"
    volumes:
      - ./user.sql:/docker-entrypoint-initdb.d/user.sql
